### ISSUE TITLE
v1.2.4 breaks my webpack build

### ISSUE THREAD

**Issue by mainstreetmark** [gluons/Font-Awesome-Icon-Chars#6]
Upgraded to v1.2.4 and webpack build failed:
`
Module not found: Error: Can't resolve 'font-awesome-icon-chars' in ...
`

If I run the command `npm install --save-dev font-awesome-icon-chars@1.2.3`, the webpack build succeeds.

**Comment by gluons** [comment]
Could you give me full error or the sample project to reproduce it?

**Comment by gluons** [comment]
It seems that `dist` directory is missing on NPM registry. 😱 
I just look on [unpkg](https://unpkg.com/font-awesome-icon-chars@1.2.4/).

I will fix it ASAP. Thank you for reporting.

**Comment by gluons** [comment]
@mainstreetmark I've republished with [`1.2.5`](https://github.com/gluons/Font-Awesome-Icon-Chars/releases/tag/v1.2.5). Please try it and tell me.

**Comment by gluons** [comment]
It appears that [`1.2.5`](https://unpkg.com/font-awesome-icon-chars@1.2.5/) resolve this issue. Now, closed.

**Comment by mainstreetmark** [comment]
Yeah, sorry.  I'm at 1.2.5 now and it works.  Thanks.
